#exersice 3.9
invetation=["sadaf","samreen","afshan"]
print(invetation[0].title()+" ,I would like to invite you for dinner")
print(invetation[1].title()+" ,I would like to invite you for dinner")
print(invetation[2].title()+" ,I would like to invite you for dinner")
print(invetation[2].title()+" ,sorry you can’t make it .")
invetation[2]="mehwish"
print(invetation[2].title()+"  you are inviting .")
print(invetation[0].title()+" is still in my list")
print(invetation[1].title()+" is still in my list")
print("Congratzz!!, I found big dinner table")
print(len(invetation))
invetation.insert(0,"iqra")
invetation.insert(2,"asiya")
invetation.append("hifza")
print(len(invetation))
print(invetation[0].title()+" ,I would like to invite you for dinner")
print(invetation[1].title()+" ,I would like to invite you for dinner")
print(invetation[2].title()+" ,I would like to invite you for dinner")
print(invetation[3].title()+" ,I would like to invite you for dinner")
print(invetation[4].title()+" ,I would like to invite you for dinner")
print(invetation[5].title()+" ,I would like to invite you for dinner")
print("Sorry I invite only..")
print(len(invetation))
inv_pop=invetation.pop()
print(inv_pop.title()+" you’re sorry you can’t invite them to dinner . ")
inv_pop=invetation.pop()
print(inv_pop.title()+" you’re sorry you can’t invite them to dinner . ")
inv_pop=invetation.pop()
print(inv_pop.title()+" you’re sorry you can’t invite them to dinner . ")
inv_pop=invetation.pop()
print(len(invetation))
print(inv_pop.title()+" you’re sorry you can’t invite them to dinner . ")
print(invetation[0].title()+" you are still invited .")
print(invetation[1].title()+" you are still invited .")
print(len(invetation))