#exersice 3.8
visit_place=["nararan","kangan","mari","kashmier","saudia"]
print("Original order of list")
print(visit_place)
print("Sorted list")
print(sorted(visit_place))
print("still original list")
print(visit_place)
print("reverse list")
visit_place.reverse()
print(visit_place)
print("original list")
visit_place.reverse()
print(visit_place)
print("sorting")
visit_place.sort()
print(visit_place)
print("change order")
visit_place.sort(reverse=True)
print(visit_place)